[platformio]
description = minimal UART protocol for ATmega328pb/p
name = UART

[env]
; to generate 'compile_commands.json' for cmaked lsp
; generate the file with: pio run -e demo -t compiledb 
extra_scripts = pre:test/compile_db_options.py

;=====================
;   EXAMPLES
;=====================

[env:demo]
platform = atmelavr
board = ATmega328PB
upload_protocol = usbasp
upload_command = /usr/bin/avrdude -c usbasp -p m328pb -U flash:w:.pio/build/demo/firmware.hex
build_flags = 
	-pedantic
	-O3
	-Os
	-DUART_BAUD_RATE=115200
build_src_filter = +<*.cpp> +<../examples/main.cpp>

[env:demo_interrupt]
platform = atmelavr
board = ATmega328PB
upload_protocol = usbasp
upload_command = /usr/bin/avrdude -c usbasp -p m328pb -U flash:w:.pio/build/demo_interrupt/firmware.hex
build_flags = 
	-pedantic
	-O3
	-Os
	-DUSE_INTERRUPT=1
	-DUART_BAUD_RATE=115200
build_src_filter = +<*.cpp> +<../examples/main_interrupt.cpp>

[env:mem_usage]
platform = atmelavr
board = ATmega328PB
build_flags =
	-pedantic
	-O3
	-Os
build_src_filter = +<*.cpp> +<../examples/main_memtest.cpp>

[env:mem_usage_interrupts]
platform = atmelavr
board = ATmega328PB
build_flags =
	-pedantic
	-O3
	-Os
	-DUSE_INTERRUPT=1
build_src_filter = +<*.cpp> +<../examples/main_memtest_interrupt.cpp>

[env:arduino]
platform = atmelavr
board = ATmega328PB
framework = arduino
build_flags =
	-pedantic
	-O3
	-Os
build_src_filter = +<*.cpp> +<../examples/arduino.cpp>

;=====================
;    SIMULATION
;=====================
;1. build elf file with pio run -e simavr_avr_test
;2. run test with pio run -e simavr_host_test
; test use firmware.elf build in step 1...so order matters
; also firmware.elf path is given in relation to .pio/build
; folder. So execute program from that folder.

[env:simavr_avr_test]
platform = atmelavr
board = ATmega328PB
build_type = debug
build_flags = 
	-O0
	-g3
	-DUSE_INTERRUPT=1
	-DBUFFER_SIZE=40
	-DUART_BAUD_RATE=9600
build_src_filter =+<*.cpp> +<../sim/simavr_avr_test.cpp> 

[env:simavr_host_test]
platform = native
platform_packages = platformio/tool-simavr
build_flags = 
	-std=c++17
	-lsimavr
	-DFIRMWARE_ELF=\"./build/simavr_avr_test/firmware.elf\"
	-I/home/mi/.platformio/packages/tool-simavr/include
build_src_filter = +<../sim/simavr_host_test.cpp>


